/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.9/samples
 */

group = "com.example"
version = "1.0.0"

plugins {
    `maven-publish`
    `version-catalog`
}

catalog {
    versionCatalog {
        library("spring-boot", "org.springframework.boot:spring-boot-starter:3.3.0")
    }
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["versionCatalog"])
        }
    }
}
